### PR TITLE
Update template.coffee

### LINKED ISSUE #7: server.js needs to use different coffee-script require()
```js
require("coffee-script")
require("./app/app.coffee")
```
needs to be

```js
require("coffee-script/register")
require("./app/app.coffee")
```

### PR DESCRIPTION
**Pull request by yyolk**
Fixes #7 & #8

### CODE REVIEW

**Comment by caseyram** [comment]
Lol, I was just about to update the code and submit this exact pull request. Nice Job yyolk!

**Comment by yyolk** [comment]
Thanks @caseyram


Now just waiting for it to be merged 😉 (since 2014…)

**Comment by EtienneLem** [comment]
Woah, I have no clue why this hasn’t been merged yet.
Sorry about.

Thanks :metal:

**Comment by yyolk** [comment]
Awesome possum!

**Pull request merged**
